/* length: 11 */
const harrySearchBooks = [
  {
    bookId: 47,
    title: '개소리에 대하여',
    coverImageUrl: 'https://image.yes24.com/goods/171435916/L',
    authors: ['해리 G. 프랭크퍼트'],
    translators: ['이윤'],
    publishedDate: '2026-01-02',
    isbn13: '9791157833870',
    category: '국내도서-인문',
    publisher: '필로소픽',
    reviewCount: 0,
    replyCount: 0,
    isRegisteredInMyLibrary: false,
  },
  {
    bookId: 33,
    title: '해리 포터와 마법사의 돌 1',
    coverImageUrl: 'https://image.yes24.com/goods/136727687/L',
    authors: ['J.K 롤링'],
    translators: ['강동혁'],
    publishedDate: '2024-11-20',
    isbn13: '9791193790403',
    category: '국내도서-소설/시/희곡',
    publisher: '문학수첩',
    reviewCount: 1,
    replyCount: 0,
    isRegisteredInMyLibrary: true,
  },
  {
    bookId: 82,
    title: '해리 포터와 마법사의 돌 2',
    coverImageUrl: 'https://image.yes24.com/goods/136727765/L',
    authors: ['J.K 롤링'],
    translators: ['강동혁'],
    publishedDate: '2024-11-20',
    isbn13: '9791193790410',
    category: '국내도서-소설/시/희곡',
    publisher: '문학수첩',
    reviewCount: 0,
    replyCount: 0,
    isRegisteredInMyLibrary: true,
  },
  {
    bookId: null,
    title: '해리 포터와 마법사의 돌 1~2권 세트',
    coverImageUrl: 'https://image.yes24.com/goods/138930460/L',
    authors: ['J.K. 롤링'],
    translators: ['강동혁'],
    publishedDate: '2024-11-20',
    isbn13: '',
    category: '국내도서-소설/시/희곡',
    publisher: '문학수첩',
    reviewCount: null,
    replyCount: null,
    isRegisteredInMyLibrary: false,
  },
  {
    bookId: null,
    title: '해리 포터와 비밀의 방 1~2권 세트',
    coverImageUrl: 'https://image.yes24.com/goods/138930471/L',
    authors: ['J.K. 롤링'],
    translators: ['강동혁'],
    publishedDate: '2024-11-20',
    isbn13: '',
    category: '국내도서-소설/시/희곡',
    publisher: '문학수첩',
    reviewCount: null,
    replyCount: null,
    isRegisteredInMyLibrary: false,
  },
  {
    bookId: null,
    title: '해리 포터와 비밀의 방 2',
    coverImageUrl: 'https://image.yes24.com/goods/136727885/L',
    authors: ['J.K 롤링'],
    translators: ['강동혁'],
    publishedDate: '2024-11-20',
    isbn13: '9791193790434',
    category: '국내도서-소설/시/희곡',
    publisher: '문학수첩',
    reviewCount: null,
    replyCount: null,
    isRegisteredInMyLibrary: false,
  },
  {
    bookId: 34,
    title: '해리 포터와 비밀의 방 1',
    coverImageUrl: 'https://image.yes24.com/goods/136727823/L',
    authors: ['J.K 롤링'],
    translators: ['강동혁'],
    publishedDate: '2024-11-20',
    isbn13: '9791193790427',
    category: '국내도서-소설/시/희곡',
    publisher: '문학수첩',
    reviewCount: 0,
    replyCount: 0,
    isRegisteredInMyLibrary: true,
  },
  {
    bookId: null,
    title: '해리 포터와 아즈카반의 죄수 1',
    coverImageUrl: 'https://image.yes24.com/goods/136727962/L',
    authors: ['J.K 롤링'],
    translators: ['강동혁'],
    publishedDate: '2024-11-20',
    isbn13: '9791193790441',
    category: '국내도서-소설/시/희곡',
    publisher: '문학수첩',
    reviewCount: null,
    replyCount: null,
    isRegisteredInMyLibrary: false,
  },
  {
    bookId: null,
    title: '심리검사의 이해와 활용',
    coverImageUrl: 'https://image.yes24.com/goods/133310924/L',
    authors: ['천성문 등저'],
    translators: [],
    publishedDate: '2024-08-30',
    isbn13: '9788999732140',
    category: '국내도서-대학교재',
    publisher: '학지사',
    reviewCount: null,
    replyCount: null,
    isRegisteredInMyLibrary: false,
  },
  {
    bookId: null,
    title: '해리엇',
    coverImageUrl: 'https://image.yes24.com/goods/5278501/L',
    authors: ['한윤섭 글/서영아 그림'],
    translators: [],
    publishedDate: '2011-06-27',
    isbn13: '9788954615044',
    category: '국내도서-어린이',
    publisher: '문학동네',
    reviewCount: null,
    replyCount: null,
    isRegisteredInMyLibrary: false,
  },

  {
    bookId: null,
    title: '해리 포터 5~7부 세트',
    coverImageUrl: 'https://image.yes24.com/goods/140113753/L',
    authors: ['J.K 롤링'],
    translators: ['강동혁'],
    publishedDate: '2024-11-27',
    isbn13: '9791193790502',
    category: '국내도서-소설/시/희곡',
    publisher: '문학수첩',
    reviewCount: null,
    replyCount: null,
    isRegisteredInMyLibrary: false,
  },
];
export const harrySearchPage1 = {
  totalCount: 11,
  nextPage: 2,
  items: harrySearchBooks.slice(0, 10),
};

export const harrySearchPage2 = {
  totalCount: 11,
  nextPage: null,
  items: harrySearchBooks.slice(10),
};
