spring:
  application:
    name: chaekchaek

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - profile
              - email
app:
  frontend:
    base-url: ${FRONTEND_BASE_URL:http://localhost:3000}
    oauth-success-path: /oauth/callback
    oauth-failure-path: /login

  auth:
    access-token:
      issuer: chaekchaek
      secret: ${JWT_SECRET}
      expiration: 30m

    refresh-token:
      expiration: 14d