spring:
  application:
    name: chaekchaek
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

aladin:
  base-url: https://www.aladin.co.kr
  ttb-key: ${ALADIN_TTB_KEY}
